# Generated by Django 5.2.12 on 2026-03-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('total_in', models.IntegerField()),
                ('total_out', models.IntegerField()),
                ('net_flow', models.IntegerField()),
                ('peak_occupancy', models.IntegerField()),
                ('min_occupancy', models.IntegerField()),
            ],
            options={
                'ordering': ['device_id', 'date'],
                'indexes': [models.Index(fields=['device_id', 'date'], name='api_dailysu_device__f6a4b1_idx')],
                'unique_together': {('device_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HourlyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('hour', models.DateTimeField(db_index=True)),
                ('total_in', models.IntegerField()),
                ('total_out', models.IntegerField()),
                ('net_flow', models.IntegerField()),
                ('has_imputed_in', models.BooleanField(default=False)),
                ('has_imputed_out', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['device_id', 'hour'],
                'indexes': [models.Index(fields=['device_id', 'hour'], name='api_hourlym_device__524f8c_idx')],
                'unique_together': {('device_id', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='OccupancySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('hour', models.DateTimeField(db_index=True)),
                ('total_in', models.IntegerField()),
                ('total_out', models.IntegerField()),
                ('net_flow', models.IntegerField()),
                ('occupancy', models.IntegerField()),
                ('occupancy_is_invalid', models.BooleanField(default=False)),
                ('has_imputed_in', models.BooleanField(default=False)),
                ('has_imputed_out', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['device_id', 'hour'],
                'indexes': [models.Index(fields=['device_id', 'hour'], name='api_occupan_device__c9c3c7_idx')],
                'unique_together': {('device_id', 'hour')},
            },
        ),
    ]
