FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python manage.py migrate
RUN python manage.py load_parquet --output-dir /app/output || true

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
